sudo: required
services: docker
language: generic

before_install:
    - curl -O https://raw.githubusercontent.com/cyber-dojo/ruby/master/install_docker.sh
    - chmod +x install_docker.sh
    - ./install_docker.sh

script:
    - ./build.sh
    - ./test.sh
    - curl -O https://raw.githubusercontent.com/cyber-dojo/ruby/master/push.sh
    - chmod +x push.sh
    - ./push.sh
