# Default values for cyber-dojo-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: "differ"

replicaCount: 1

volumes:
  - name: differ-tmp-dir
    emptyDir:
      medium: Memory
      sizeLimit: "64Mi"

service:
  port: 4567

containers:
  - name: differ
    image: cyberdojo/differ
    tag: ""
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
      - name: differ-tmp-dir
        mountPath: /tmp
        readOnly: false
    resources:
      limits:
       memory: 128Mi
      requests:
       memory: 128Mi
      livenessProbe:
        path: /sha
        port: 4567
      readinessProbe:
        path: /ready?
        port: 4567

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
