name: Deploy-manually

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag (short commit SHA - first 7 digits)'
        required: true

jobs:
  deploy_to_beta:
    uses: ./.github/workflows/sub_deploy_to_beta.yml
    with:
      IMAGE_TAG: ${{ github.event.inputs.image_tag }}

  deploy_to_prod:
    uses: ./.github/workflows/sub_deploy_to_prod.yml
    with:
      IMAGE_TAG: ${{ github.event.inputs.image_tag }}
