name: Sub - approve-deployment

on:
  workflow_call:
    secrets:
      KOSLI_API_TOKEN:
        required: true
    inputs:
      KOSLI_HOST:
        default: https://app.kosli.com
        required: false
        type: string
      IMAGE_TAG:
        required: true
        type: string
      KOSLI_ENVIRONMENT:
        required: true
        type: string


env:
  KOSLI_DRY_RUN: ${{ vars.KOSLI_DRY_RUN }}
  KOSLI_HOST: ${{ inputs.KOSLI_HOST }}
  KOSLI_ORG: ${{ vars.KOSLI_ORG }}
  KOSLI_FLOW: ${{ vars.KOSLI_FLOW }}
  KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}

jobs:

  to-env:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Kosli CLI
        uses: kosli-dev/setup-cli-action@v2
        with:
          version: ${{ vars.KOSLI_CLI_VERSION }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Report approval of deployment
        run: |
          IMAGE_NAME=cyberdojo/${{ env.KOSLI_FLOW }}:${{ inputs.IMAGE_TAG }}          
          docker pull ${IMAGE_NAME}
          kosli report approval ${IMAGE_NAME} \
            --artifact-type=docker \
            --environment=${{ inputs.KOSLI_ENVIRONMENT }} \
            --approver="${{ github.actor }}"

      - name: Report expected deployment to Kosli
        run: |
          IMAGE_NAME=cyberdojo/${{ env.KOSLI_FLOW }}:${{ inputs.IMAGE_TAG }}          
          docker pull ${IMAGE_NAME}
          kosli expect deployment ${IMAGE_NAME} \
            --artifact-type=docker \
            --description="Deployed to ${{ inputs.KOSLI_ENVIRONMENT }} in Github Actions pipeline" \
            --environment=${{ inputs.KOSLI_ENVIRONMENT }}
